'use client'

import { Code2, Flame, Lock, Sparkles, Target, Trophy } from 'lucide-react'
import type { ReactNode } from 'react'
import { ACHIEVEMENTS, ACTIVITY_DAYS, RECENT_ASSESSMENTS, TIME_SPENT, type Achievement } from '@/lib/learning-mock-data'

const ICONS: Record<Achievement['icon'], typeof Sparkles> = { sparkles: Sparkles, flame: Flame, code: Code2, target: Target }

function Card({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <section className={`rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-6 ${className}`}>{children}</section>
}

function ActivityHeatmap() {
  return <Card className="overflow-hidden"><div className="flex items-start justify-between gap-4"><div><h2 className="font-display font-bold text-lg text-[var(--foreground)]">Learning Activity</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">A year of practice, one day at a time.</p></div><div className="hidden items-center gap-1 text-[0.7rem] text-[var(--muted-foreground)] sm:flex"><span>Less</span>{[0, 1, 2, 3, 4].map(level => <span key={level} className="size-3 rounded-sm border border-[var(--border)]" style={{ background: level === 0 ? 'var(--background)' : `color-mix(in srgb, var(--accent-green) ${level * 20}%, var(--background))` }} />)}<span>More</span></div></div>
    <div className="mt-6 overflow-x-auto pb-2"><div className="grid w-max grid-flow-col grid-rows-7 gap-1">{ACTIVITY_DAYS.map(day => <div key={day.date} className="group relative size-3 rounded-[3px] border border-[var(--border)]" style={{ background: day.count === 0 ? 'var(--background)' : `color-mix(in srgb, var(--accent-green) ${day.count * 20}%, var(--background))` }}><span className="pointer-events-none absolute bottom-full left-1/2 z-10 mb-2 hidden w-max -translate-x-1/2 rounded-lg border border-[var(--border)] bg-[var(--surface)] px-2 py-1 text-[0.65rem] text-[var(--foreground)] shadow-sm group-hover:block">{day.date} · {day.minutes} min</span></div>)}</div></div>
    <div className="mt-4 flex items-center gap-1 text-[0.7rem] text-[var(--muted-foreground)] sm:hidden"><span>Less</span>{[0, 1, 2, 3, 4].map(level => <span key={level} className="size-3 rounded-sm border border-[var(--border)]" style={{ background: level === 0 ? 'var(--background)' : `color-mix(in srgb, var(--accent-green) ${level * 20}%, var(--background))` }} />)}<span>More</span></div>
  </Card>
}

function TimeChart() {
  const max = Math.max(...TIME_SPENT.map(point => point.minutes))
  return <Card><div><h2 className="font-display font-bold text-lg text-[var(--foreground)]">Time Spent Learning</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">Minutes practiced over the last two weeks.</p></div><div className="mt-6 flex h-48 items-end gap-2 border-b border-[var(--border)] pb-1">{TIME_SPENT.map(point => <div key={point.label} className="group relative flex h-full min-w-0 flex-1 flex-col justify-end"><span className="pointer-events-none absolute bottom-[calc(100%+0.35rem)] left-1/2 hidden -translate-x-1/2 rounded-lg border border-[var(--border)] bg-[var(--surface)] px-2 py-1 text-[0.65rem] text-[var(--foreground)] shadow-sm group-hover:block">{point.minutes} min</span><div className="rounded-t-md bg-[var(--accent-blue)]/70 transition-colors group-hover:bg-[var(--accent-blue)]" style={{ height: `${(point.minutes / max) * 100}%` }} /><span className="mt-2 text-center text-[0.6rem] text-[var(--muted-foreground)]">{point.label}</span></div>)}</div></Card>
}

export default function DashboardContent() {
  return <div className="space-y-6"><header><p className="mb-3 text-xs font-semibold uppercase tracking-[0.14em] text-[var(--accent-blue)]">Your progress</p><h1 className="font-display text-4xl font-bold tracking-tight text-[var(--foreground)]">Learning Dashboard</h1><p className="mt-4 max-w-[42rem] text-[var(--muted-foreground)]">A simple view of your recent practice, milestones, and learning rhythm.</p></header>
    <div className="grid gap-6 xl:grid-cols-3"><Card className="xl:col-span-2"><div className="mb-5 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[var(--accent-blue)]/10 text-[var(--accent-blue)]"><Target size={17} /></span><div><h2 className="font-display font-bold text-lg text-[var(--foreground)]">Recent Assessments</h2><p className="text-xs text-[var(--muted-foreground)]">Your latest quiz results.</p></div></div><div className="grid gap-3 sm:grid-cols-3">{RECENT_ASSESSMENTS.map(item => <div key={item.title} className="rounded-2xl border border-[var(--border)] bg-[var(--background)] p-4"><p className="text-sm font-semibold text-[var(--foreground)]">{item.title}</p><p className="mt-1 text-xs text-[var(--muted-foreground)]">{item.date}</p><div className="mt-4 flex items-center justify-between"><span className="font-display text-xl font-bold text-[var(--foreground)]">{item.score}%</span><span className={`rounded-full px-2 py-1 text-[0.65rem] font-semibold ${item.status === 'Passed' ? 'bg-[var(--accent-green)]/10 text-[var(--accent-green)]' : 'bg-[var(--accent-orange)]/10 text-[var(--accent-orange)]'}`}>{item.status}</span></div></div>)}</div></Card>
      <Card><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[var(--accent-yellow)]/10 text-[var(--accent-yellow)]"><Trophy size={17} /></span><div><h2 className="font-display font-bold text-lg text-[var(--foreground)]">Achievements</h2><p className="text-xs text-[var(--muted-foreground)]">Keep collecting momentum.</p></div></div><div className="mt-5 grid grid-cols-2 gap-3">{ACHIEVEMENTS.map(achievement => { const Icon = ICONS[achievement.icon]; return <div key={achievement.title} className={`rounded-2xl border border-[var(--border)] p-3 ${achievement.unlocked ? 'bg-[var(--background)]' : 'opacity-55'}`}><div className={`mb-3 grid size-8 place-items-center rounded-lg ${achievement.unlocked ? 'bg-[var(--accent-yellow)]/10 text-[var(--accent-yellow)]' : 'bg-[var(--background)] text-[var(--muted-foreground)]'}`}>{achievement.unlocked ? <Icon size={15} /> : <Lock size={14} />}</div><p className="text-xs font-semibold text-[var(--foreground)]">{achievement.title}</p><p className="mt-1 text-[0.65rem] leading-relaxed text-[var(--muted-foreground)]">{achievement.description}</p></div> })}</div></Card></div>
    <div className="grid gap-6 xl:grid-cols-2"><ActivityHeatmap /><TimeChart /></div>
  </div>
}
